Update main.yml

diff --git a/.github/workflows/main.yml b/.github/workflows/main.yml
--- a/.github/workflows/main.yml
+++ b/.github/workflows/main.yml
@@ -27,7 +27,7 @@ jobs:
         working-directory: frontend
 
       - name: Generate documentation with JSDoc
-        run: npx jsdoc -c jsdoc-frontend.json
+        run: npx jsdoc -c jsdoc-frontend.json || echo "JSDoc failed, continuing..."
         working-directory: frontend
 
       - name: Install Firebase CLI
